version: "3.8"
services:
  grafana:
    image: grafana/grafana-oss
    container_name: grafana
    restart: unless-stopped
    environment:
      - GF_SERVER_ROOT_URL=http://my.grafana.server/
      - GF_INSTALL_PLUGINS=grafana-clock-panel
    ports:
     - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
  influxdb:
    image: influxdb
    container_name: influxdb
    restart: always
    hostname: influxdb
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin
      - DOCKER_INFLUXDB_INIT_ORG=atso
      - DOCKER_INFLUXDB_INIT_BUCKET=my-bucket
    ports:
      - '8086:8086'
    volumes:
      - ./influxdb:/var/lib/influxdb

volumes:
  grafana-storage: { }